name: Auto merge connector PRs Cron

on:
  schedule:
    # Every 2 hours on the hour.
    - cron: "0 */2 * * *"
  workflow_dispatch:
jobs:
  run_auto_merge:
    name: Run auto-merge
    runs-on: ubuntu-24.04
    steps:
      - name: Authenticate as GitHub App
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: get-app-token
        with:
          owner: "airbytehq"
          repositories: "airbyte"
          app-id: ${{ secrets.OCTAVIA_BOT_HOARD_APP_ID }}
          private-key: ${{ secrets.OCTAVIA_BOT_HOARD_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.11"
          check-latest: true
          update-environment: true
      - name: Install and configure Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: 1.8.5
      - name: Run auto merge
        shell: bash
        working-directory: airbyte-ci/connectors/auto_merge
        env:
          GITHUB_TOKEN: ${{ steps.get-app-token.outputs.token }}
          AUTO_MERGE_PRODUCTION: ${{ vars.ENABLE_CONNECTOR_AUTO_MERGE }}
        run: |
          poetry install
          poetry run auto-merge
